version: 2
project_name: xipher
env:
  - CGO_ENABLED=0
builds:

  - id: xipher-cli
    binary: xipher
    main: ./app/cmd
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - linux_arm
      - windows_amd64
      - windows_arm64
    flags: "-mod=readonly"
    ldflags:
      - -X dev.shib.me/xipher.version={{.Version}}
      - -X dev.shib.me/xipher.commitDate={{.CommitDate}}
      - -X dev.shib.me/xipher.fullCommit={{.FullCommit}}
      - -X dev.shib.me/xipher.releaseURL={{.ReleaseURL}}

  - id: xipher-wasm
    binary: xipher
    main: ./app/wasm
    targets:
      - js_wasm
    flags: "-mod=readonly"
    ldflags:
      - -X dev.shib.me/xipher.version={{.Version}}
      - -X dev.shib.me/xipher.commitDate={{.CommitDate}}
      - -X dev.shib.me/xipher.fullCommit={{.FullCommit}}
      - -X dev.shib.me/xipher.releaseURL={{.ReleaseURL}}

archives:
  - id: xipher-cli
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format: zip
    builds:
      - xipher-cli
  - id: xipher-wasm
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format: zip
    files:
      - wasm_exec.js
    builds:
      - xipher-wasm

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-dev"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpms:
  - vendor: Shibly Meeran
    homepage: https://shib.me
    maintainer: Shibly Meeran <shibme@shib.me>
    formats:
      - apk
      - deb
      - rpm

brews:
  - ids:
      - xipher-cli
    name: xipher
    homepage: "https://dev.shib.me/xipher"
    description: "Xipher is a curated collection of cryptographic primitives put together to perform key/password based asymmetric encryption."
    license: "MIT"
    commit_author:
      name: Shibly Meeran
      email: shibme@shib.me
    repository:
      owner: shibme
      name: homebrew-tap
      branch: main
      git:
        url: 'git@github.com:shibme/homebrew-tap.git'
        private_key: '{{ .Env.HOMEBREW_SSH_KEY }}'
