name: Publish Xipher Web

on:
  workflow_dispatch:
  workflow_call:

jobs:

  pages:
    name: Deploy Xipher Web to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: "pages"
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download wasm files from latest release
        uses: robinraju/release-downloader@v1.11
        with:
          latest: true
          fileName: '*wasm*'
      - name: Add WASM files to web directory
        run: |
          mkdir -p web/wasm
          unzip xipher_js_wasm.zip -d web/wasm/
      - name: Downloading StreamSaver.js to web directory
        run: |
          curl -o web/js/StreamSaver.js https://cdn.jsdelivr.net/npm/streamsaver@latest/StreamSaver.min.js
      - name: Setting commit sha in service-worker.js
        run: |
          sed -i "s/xipher-cache/xipher-${{ github.sha }}/g" web/js/service-worker.js
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact from web directory
        uses: actions/upload-pages-artifact@v3
        with:
          path: web
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
