name: Deploy static content to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare pages directory
        run: |
          cp scripts/install/* pages/
      - uses: robinraju/release-downloader@v1.10
        with:
          latest: true
          fileName: '*wasm*'
      - name: Add WASM files to pages directory
        run: |
          unzip -n xipher_js_wasm.zip
          mkdir -p pages/wasm
          mv wasm_exec.js pages/wasm/
          mv xipher.wasm pages/wasm/
      - name: Checkout xenigma
        uses: actions/checkout@v4
        with:
          repository: shibina3/xenigma
          path: xenigma
      - name: Setup Node.js
        uses: actions/setup-node@v4
      - name: Install node dependencies
        run: npm -C xenigma ci
      - name: Build Xenigma
        run: npm -C xenigma run build
      - name: Add pages from Xenigma
        run: mv xenigma/build pages/web
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
